apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndana_shop_manager
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ndana_shop_manager
  template:
    metadata:
      labels:
        app: ndana_shop_manager
    spec:
      containers:
      - name: ndana-shop-deployment
        image: patienceman/ndana_shop_manager:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
