apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndana_shop_manager
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: ndana_shop_manager
        image: patienceman/ndana_shop_manager:latest
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: ndana_shop_manager
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
