apiVersion: v1
kind: Service
metadata:
  name: ndana_shop_manager
  namespace: default
spec:
  type: NodePort
  selector:
    app: ndana_shop_manager
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
    type: LoadBalancer
